#pragma config(Sensor, S1,     touchLeft,      sensorTouch)
#pragma config(Sensor, S2,     touchRight,     sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          backMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "motorpattern.h"
#include "motorpattern.c"

task main(){

	functiontest()
	//josh was here
}
