#pragma config(Sensor, S1,     touchLeft,      sensorTouch)
#pragma config(Sensor, S2,     touchRight,     sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          leftMotor,     tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          backMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "motorpattern.h"
#include "motorpattern.c" // robotC's compiler doesn't do multiple C files automatically, I'm sorry style gods

task main()
{
	wait1Msec(50);

	while(1)
	{
		int dist = SensorValue[sonar];
		int hunt = 0;

		//if (SensorValue[light] < 45) // found arena edge
		//{
		//	lturn(500);
		//	wait1Msec(500);
		//	forward(500);
		//}

		if (SensorValue[touchLeft] == 0) // unpressed
			hunt = 3;
		//else if (SensorValue[touchRight] == 1)
		//	hunt = 4;

		if (dist > 50)
			hunt = 1;
		else
			hunt = 2;

		switch(hunt)
		{
		case 1:
			lturn();
			hunt = 0;
			break;

		case 2:
			forward();
			hunt = 0;
			break;

		case 3:
			lturn();
			hunt = 0;
			break;

		case 4:
			rturn();
			hunt = 0;
			break;

		}
	}
}
